### PR TITLE
Update to 3.5.9

### PR DESCRIPTION
**Pull request by ocefpaf**
@blink1073 are you, or do you know anyone, interested in becoming a maintainer of this recipe?

### CODE REVIEW

**Comment by blink1073** [comment]
@ocefpaf, I confess I haven't learned how to maintain a conda-forge recipe yet.  I'll take this as a nudge to learn ;).

**Comment by ocefpaf** [comment]
> @ocefpaf, I confess I haven't learned how to maintain a conda-forge recipe yet.

That is a problem on our end :wink: 

> I'll take this as a nudge to learn ;)

The maintainer "job" is pretty light. It consists of sending PRs like this one, to update the package, and to merge an eventual automatic PR that re-renders the `feedstock` (the recipe repository).

Ideally, as the dev of `oct2py`, you would have a better vantage point to check the recipe health, like dependencies that were added/removed in a new version, etc. I will add you in a new PR and you will get commit rights to this repository.

**Comment by blink1073** [comment]
@ocefpaf, where did you get the sha256 hash from?

**Comment by ocefpaf** [comment]
> @ocefpaf, where did you get the sha256 hash from?

Good question! And one that we shamefully answer:

Download it from a trusted source, compute it locally, and add it to the recipe. Sadly GitHub does not provide any checksum from the archived releases.

**Comment by blink1073** [comment]
I added this to to my release script: https://github.com/blink1073/oct2py/commit/e3eb7b6d753a0c69b635dcc52591b3e977734423

**Comment by blink1073** [comment]
Whoops, updated to use the tar file: https://github.com/blink1073/oct2py/commit/94019148f582ec72481ecbc7d08caf28d10221dd

**Comment by ocefpaf** [comment]
Awesome!

**Pull request merged**
